## Association Rule Mining Using Apriori Algorithm

In [1]:
%pip install mlxtend==0.23.1 -q

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
data = pd.read_csv("../data/groceries.csv")

In [4]:
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

In [5]:
basket_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [6]:
basket_sets.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
baskets_sets_bool = basket_sets.astype(bool)
apriori(baskets_sets_bool, min_support=0.02)

      support         itemsets
0    0.028155              (1)
1    0.054369              (8)
2    0.032039              (9)
3    0.027508             (10)
4    0.072492             (11)
..        ...              ...
105  0.022977       (154, 163)
106  0.033981       (162, 158)
107  0.055987       (162, 163)
108  0.022977  (121, 162, 101)
109  0.022977  (162, 163, 101)

[110 rows x 2 columns]

In [8]:
baskets_sets_bool = basket_sets.astype(bool)
apriori(baskets_sets_bool, min_support=0.02, use_colnames = True)

      support                                         itemsets
0    0.028155                                       (UHT-milk)
1    0.054369                                           (beef)
2    0.032039                                        (berries)
3    0.027508                                      (beverages)
4    0.072492                                   (bottled beer)
..        ...                                              ...
105  0.022977                         (yogurt, tropical fruit)
106  0.033981                 (whipped/sour cream, whole milk)
107  0.055987                             (yogurt, whole milk)
108  0.022977  (other vegetables, root vegetables, whole milk)
109  0.022977           (yogurt, other vegetables, whole milk)

[110 rows x 2 columns]

In [9]:
df_combo = basket_sets.astype(bool)

frequent_itemsets = apriori(df_combo, min_support=0.002, use_colnames = True)

frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(lambda x: len(x))

frequent_itemsets

       support                                           itemsets  length
0     0.007120                            (Instant food products)       1
1     0.028155                                         (UHT-milk)       1
2     0.002913                                 (abrasive cleaner)       1
3     0.003560                                 (artif. sweetener)       1
4     0.014887                                    (baking powder)       1
...        ...                                                ...     ...
2313  0.002265  (whole milk, root vegetables, yogurt, citrus f...       5
2314  0.002589  (whole milk, yogurt, whipped/sour cream, citru...       5
2315  0.002265  (whole milk, yogurt, whipped/sour cream, other...       5
2316  0.002265  (whole milk, tropical fruit, root vegetables, ...       5
2317  0.002265  (whole milk, tropical fruit, yogurt, whipped/s...       5

[2318 rows x 3 columns]

In [10]:
frequent_itemsets[(frequent_itemsets["length"] >=3)]

       support                                           itemsets  length
1260  0.002589        (bottled water, UHT-milk, other vegetables)       3
1261  0.002265                    (bottled water, soda, UHT-milk)       3
1262  0.002589      (other vegetables, baking powder, whole milk)       3
1263  0.002265    (whipped/sour cream, baking powder, whole milk)       3
1264  0.002589                        (beef, berries, whole milk)       3
...        ...                                                ...     ...
2313  0.002265  (whole milk, root vegetables, yogurt, citrus f...       5
2314  0.002589  (whole milk, yogurt, whipped/sour cream, citru...       5
2315  0.002265  (whole milk, yogurt, whipped/sour cream, other...       5
2316  0.002265  (whole milk, tropical fruit, root vegetables, ...       5
2317  0.002265  (whole milk, tropical fruit, yogurt, whipped/s...       5

[1058 rows x 3 columns]

In [11]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.9)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,"(hamburger meat, curd)",(whole milk),0.003236,0.256634,0.003236,1.000000,3.896595,0.002406,inf,0.745779
1,"(frozen fish, root vegetables)",(whole milk),0.002265,0.256634,0.002265,1.000000,3.896595,0.001684,inf,0.745054
2,"(sausage, bottled water, soda)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,0.002749,9.494175,0.852452
3,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,0.002669,9.248544,0.827801
4,"(pip fruit, butter, whole milk)",(other vegetables),0.003560,0.192557,0.003236,0.909091,4.721161,0.002551,8.881877,0.791004

In [12]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1.5)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Instant food products),(other vegetables),0.007120,0.192557,0.002265,0.318182,1.652406,0.000894,1.184250,0.397653
1,(other vegetables),(Instant food products),0.192557,0.007120,0.002265,0.011765,1.652406,0.000894,1.004700,0.488978
2,(Instant food products),(root vegetables),0.007120,0.110032,0.002265,0.318182,2.891711,0.001482,1.305286,0.658875
3,(root vegetables),(Instant food products),0.110032,0.007120,0.002265,0.020588,2.891711,0.001482,1.013752,0.735065
4,(bottled water),(UHT-milk),0.111974,0.028155,0.006472,0.057803,2.053020,0.003320,1.031467,0.577587

In [15]:
rules[(rules["lift"]>=5) & (rules["confidence"]>=0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5573,"(sausage, bottled water, soda)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,0.002749,9.494175,0.852452
5574,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,0.002669,9.248544,0.827801
5838,"(sausage, rolls/buns, canned beer)",(shopping bags),0.002589,0.082848,0.002265,0.875000,10.561523,0.002051,7.337217,0.907667
6586,"(dessert, whipped/sour cream, other vegetables)",(yogurt),0.002913,0.136893,0.002589,0.888889,6.493302,0.002190,7.767961,0.848466
6641,"(pastry, frankfurter, other vegetables)",(rolls/buns),0.002265,0.194498,0.002265,1.000000,5.141431,0.001825,inf,0.807331
6768,"(hamburger meat, pork, whole milk)",(other vegetables),0.002589,0.192557,0.002589,1.000000,5.193277,0.002090,inf,0.809539